name: Test Solution
description: Test solution

inputs:
  working-directory:
    description: "The working directory containing the solution or project to build"
    required: true

  configuration:
    description: "The configuration to build and test"
    required: true

  version-prefix:
    description: VersionPrefix value
    required: false

  version-suffix:
    description: VersionSuffix value
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Setup test environment
      shell: bash
      run: |
        chmod +x ./localstack/startup.sh
        docker compose up --detach --build --wait
      working-directory: ./src/test-env

    - name: Run tests - ${{ inputs.configuration }}
      uses: wen-yan/basalt-shared/.github/actions/dotnet-command@v1
      with:
        command: test
        configuration: ${{ inputs.configuration }}
        working-directory: ./src

    - name: Stop test environment
      shell: bash
      run: docker compose down
      working-directory: ./src/test-env
